import { Alex_Brush, Libre_Baskerville } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/general/Navbar";

const libreBaskerville = Libre_Baskerville({
  variable: "--font-libreBaskerville",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const alexBrush = Alex_Brush({
  variable: "--font-alexBrush",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${libreBaskerville.variable} ${alexBrush.variable}  antialiased `}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
