import { Alex_Brush, Libre_Baskerville } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/general/Navbar";
import MobileNav from "@/components/general/MobileNav";
import LenisScroll from "@/components/general/Lenis";

const libreBaskerville = Libre_Baskerville({
  variable: "--font-libreBaskerville",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const alexBrush = Alex_Brush({
  variable: "--font-alexBrush",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${libreBaskerville.variable} ${alexBrush.variable} bg-lightGreen`}
      >
        <div className='md:flex md:h-screen'>
          {/* Navbar: Fixed width, does not overlap content */}
          <Navbar />
          <MobileNav />
          <LenisScroll />

          {/* Content section: Takes up remaining space */}
          <main className='md:flex-1 md:pl-[22rem]'>{children}</main>
        </div>
      </body>
    </html>
  );
}
